export { ReactComponent as AccessIcon } from './icons/access-icon.svg';
export { ReactComponent as ArrowIcon } from './icons/arrow-icon.svg';
export { ReactComponent as CheckIcon } from './icons/check-icon.svg';
export { ReactComponent as CloseIcon } from './icons/close-icon.svg';
export { ReactComponent as ErrorIcon } from './icons/error-icon.svg';
export { ReactComponent as FolderIcon } from './icons/folder-icon.svg';
export { ReactComponent as PlusIcon } from './icons/plus-icon.svg';
export { ReactComponent as PreloaderArrowsIcon } from './icons/preloader-arrows-icon.svg';
export { ReactComponent as TrashcanIcon } from './icons/trashcan-icon.svg';
